#!/usr/bin/env bash

# Source this file before preflight/training on the PVMMoE server:
#   source scripts/use_pvmoe_local_weights.sh
PRETRAINED_MODELS_ROOT="${PRETRAINED_MODELS_ROOT:-/data/PVMMoE/PRETRAINED_MODELS}"

export SUNDIAL_WEIGHT_DIR="${SUNDIAL_WEIGHT_DIR:-$PRETRAINED_MODELS_ROOT/sundial-base-128m}"
export CHRONOS2_WEIGHT_DIR="${CHRONOS2_WEIGHT_DIR:-$PRETRAINED_MODELS_ROOT/chronos2}"
export TIMEMOE_WEIGHT_DIR="${TIMEMOE_WEIGHT_DIR:-$PRETRAINED_MODELS_ROOT/TimeMoE-50M}"
export TIMEMOE_200M_WEIGHT_DIR="${TIMEMOE_200M_WEIGHT_DIR:-$PRETRAINED_MODELS_ROOT/TimeMoE-200M}"
export TIREX_WEIGHT_DIR="${TIREX_WEIGHT_DIR:-$PRETRAINED_MODELS_ROOT/TiRex}"
export TIMESFM_WEIGHT_DIR="${TIMESFM_WEIGHT_DIR:-$PRETRAINED_MODELS_ROOT/TimesFM}"

export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1

printf '%s\n' \
  "Sundial: $SUNDIAL_WEIGHT_DIR" \
  "Chronos2: $CHRONOS2_WEIGHT_DIR" \
  "TimeMoE-50M: $TIMEMOE_WEIGHT_DIR" \
  "TimeMoE-200M: $TIMEMOE_200M_WEIGHT_DIR" \
  "TiRex: $TIREX_WEIGHT_DIR" \
  "TimesFM: $TIMESFM_WEIGHT_DIR"
